### PR TITLE
Add TAN handling

### PR DESCRIPTION
**Pull request by aklaiber**

### CODE REVIEW

**Comment by agross** [comment]
Just tested with my netbank account:

```
RuntimeError (HNHBK:1:3+000000000535+300+yLqFKf41am0BAABW?+h3bpkThCgQA+2+yLqFKf41am0BAABW?+h3bpkThCgQA:2'HNVSK:998:3+PIN:2+998+1+2::S7eFKf41am0BAABW?+h3bpkThCgQA+1:20190925:230127+2:2:13:@5@NOKEY:5:1+280:20090500:1234567890:V:1:1+0'HNVSD:999:1+@287@HNSHK:2:4+PIN:2+901+14999986+1+1+2::S7eFKf41am0BAABW?+h3bpkThCgQA+2+1:20190925:230127+1:999:1+6:10:16+280:20090500:1234567890:S:0:0'HIRMG:3:2+9050::Die Nachricht enth�lt Fehler.'HIRMS:4:2:3+9010::Auftrag wegen genereller Fehler in Auftragsnachricht nicht verarbeitet.'HNSHA:5:2+14999986''HNHBS:6:1+2')```

**Comment by aklaiber** [comment]
Could you send me your complete log output (without PIN and TAN ;-))?

**Comment by agross** [comment]
This is the log of the irb session: [log.txt](https://github.com/fintastic/hbci/files/3658323/log.txt)

**Comment by aklaiber** [comment]
The session and dialog init seems ok. Please replace the 2 for the`security_profile.version`  with a 1 and try again.

https://github.com/fintastic/hbci/blob/4d8faf94b578b6c227895373a63592cdc62cda97/lib/hbci/services/balance_receiver.rb#L49

https://github.com/fintastic/hbci/blob/4d8faf94b578b6c227895373a63592cdc62cda97/lib/hbci/services/balance_receiver.rb#L96

if this doesn't work could you test the `BalanceReceiver` with a TAN?

```ruby
Hbci::Connector.open(credentials) do |connector|
  Hbci::Dialog.open(connector, tan: '******') do |dialog|
    puts Hbci::Services::BalanceReceiver.new(connector, dialog, iban).perform
  end
end
```

**Comment by agross** [comment]
> Please replace the 2 for thesecurity_profile.version with a 1 and try again.

`hnshk.security_profile.version = 1` also results in a `RuntimeError`.

> if this doesn't work could you test the BalanceReceiver with a TAN?

Which TAN should I use? netbank delivers them via SMS. I haven't used iTAN in years.

**Comment by aklaiber** [comment]
Very difficult to debug without a netbank account ;-) The only different is the  HKSAL Version (5 and 7) but I didn't change this Segment.  

The master brach is still running with your netbank account? If yes, could you send me the HBCI responses and requests?

**Comment by agross** [comment]
master yields:

```
RuntimeError (HNHBK:1:3+000000000447+300+iiYeD0q9i20BAAAbBNZ2pkThCgQA+2+iiYeD0q9i20BAAAbBNZ2pkThCgQA:2'HNVSK:998:3+PIN:1+998+1+2::0+1:20191002:112722+2:2:13:@5@NOKEY:6:1+280:20090500:1234567890:V:1:1+0'HNVSD:999:1+@229@HNSHK:2:4+PIN:1+901+22999978+1+1+2::0+1+1:20191002:112722+1:999:1+6:10:16+280:20090500:1234567890:S:0:0'HIRMG:3:2+9050::Die Nachricht enth�lt Fehler.'HIRMS:4:2:3+9075::Starke Kundenauthentifizierung notwendig.'HNSHA:5:2+22999978''HNHBS:6:1+2')
	from /Users/agross/Downloads/fintastic-hbci/lib/hbci/services/balance_receiver.rb:14:in `perform'
	from netbank.rb:11:in `block (2 levels) in irb_binding'
	from /Users/agross/Downloads/fintastic-hbci/lib/hbci/dialog.rb:15:in `open'
	from netbank.rb:10:in `block in irb_binding'
	from /Users/agross/Downloads/fintastic-hbci/lib/hbci/connector.rb:10:in `open'
	from netbank.rb:9
	from bin/console:15:in `<top (required)>'
```

**Comment by aklaiber** [comment]
Sorry I need the HBCI request. Could you set a `puts` on this position (https://github.com/fintastic/hbci/blob/master/lib/hbci/services/balance_receiver.rb#L11) and send me the output?

**Comment by agross** [comment]
Sure. On master:

```diff
diff --git a/lib/hbci/services/balance_receiver.rb b/lib/hbci/services/balance_receiver.rb
index e5f54c3..f57a7f3 100644
--- a/lib/hbci/services/balance_receiver.rb
+++ b/lib/hbci/services/balance_receiver.rb
@@ -8,7 +8,7 @@ module Hbci
           hnvsd.add_segment(build_hksal)
         end
         request_message.compile
-
+        puts request_message
         @response = Response.new(connector.post(request_message))

         raise @response.to_s unless request_successful?
```

```
HNHBK:1:3+000000000367+300+PqOWyITui20BAAAbBNZ2pkThCgQA+2'HNVSK:998:3+PIN:1+998+1+1::0+1:20191002:121002+2:2:13:@5@NOKEY:6:1+280:20090500:1234567890:V:1:1+0'HNVSD:999:1+@180@HNSHK:2:4+PIN:1+901+11999989+1+1+1::0+1+1:20191002:121002+1:999:1+6:10:16+280:20090500:1234567890:S:0:0'HKSAL:3:5+1708538::280:20090500+N'HNSHA:4:2+11999989++secret''HNHBS:5:1+2'
```

Login (`1234567890`) and password (`secret`) have been replaced.

**Comment by aklaiber** [comment]
VR-Bank, Postbank, Consorsbank and HVB works without problems. Unfortunately I'm not able to reproduce this error without a netbank account.

**Comment by agross** [comment]
Juts an idea off the top of my head: I have a `+` sign in my netbank password (as well as `.`, `&` and `*`). It seems HBCI uses plus signs to separate data fields. Could it be that my password needs to be encoded before transmitting it?

**Pull request merged**
